import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Terminal, BookOpen, Cpu } from "lucide-react"

export default function AlpacaDocsPage() {
  return (
    <div className="container mx-auto p-6 max-w-5xl">
      <div className="flex items-center gap-4 mb-8">
        <div className="p-3 bg-emerald-600 rounded-full">
          <Terminal className="w-8 h-8 text-white" />
        </div>
        <div>
          <h1 className="text-3xl font-bold text-foreground">Alpaca CLI Integration</h1>
          <p className="text-muted-foreground">Command-line interface for Trading and Market Data APIs</p>
        </div>
      </div>
      <div className="grid gap-6 md:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><BookOpen className="w-5 h-5"/> Installation</CardTitle>
            <CardDescription>Get the CLI running on your machine</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="bg-muted p-3 rounded-md font-mono text-sm">go install github.com/alpacahq/cli/cmd/alpaca@latest</div>
            <p className="text-sm text-muted-foreground">Or via Homebrew (macOS/Linux):</p>
            <div className="bg-muted p-3 rounded-md font-mono text-sm">brew install alpacahq/tap/cli</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><Cpu className="w-5 h-5"/> Authentication</CardTitle>
            <CardDescription>Connect to Paper or Live trading</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="bg-muted p-3 rounded-md font-mono text-sm">alpaca profile login --api-key</div>
            <p className="text-sm text-muted-foreground">For live trading, add the <code className="bg-muted-foreground/50 px-1 rounded">--live</code> flag. Environment variables <code className="bg-muted-foreground/50 px-1 rounded">ALPACA_API_KEY</code> and <code className="bg-muted-foreground/50 px-1 rounded">ALPACA_SECRET_KEY</code> are supported for automation.</p>
          </CardContent>
        </Card>
      </div>
      <Card className="mt-6">
        <CardHeader><CardTitle>Core Capabilities</CardTitle></CardHeader>
        <CardContent>
          <ul className="grid gap-3 md:grid-cols-2 text-sm">
            <li className="flex items-start gap-2"><span className="text-emerald-500">✓</span> <strong>Trade:</strong> Submit, replace, and cancel orders.</li>
            <li className="flex items-start gap-2"><span className="text-emerald-500">✓</span> <strong>Market Data:</strong> Pull bars, quotes, trades, and screeners.</li>
            <li className="flex items-start gap-2"><span className="text-emerald-500">✓</span> <strong>Account:</strong> Check balances, positions, and history.</li>
            <li className="flex items-start gap-2"><span className="text-emerald-500">✓</span> <strong>Automate:</strong> Pipe JSON output into scripts or AI agents.</li>
          </ul>
        </CardContent>
      </Card>
      <div className="mt-6 p-4 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-lg">
        <p className="text-sm text-amber-800 dark:text-amber-200">
          <strong>Disclosure:</strong> Insights generated by the CLI and connected AI agents are for educational purposes only. Alpaca does not recommend specific securities. Past performance does not guarantee future results.
        </p>
      </div>
    </div>
  )
}
